### PR TITLE
Added Rock paper scissors game.

### PR DESCRIPTION
**Pull request by theanujdev**
Game that runs in terminal.

### CODE REVIEW

**Review by Aayush-hub — COMMENTED** [review]
Plz limit number of tries to make it indulging.

**Comment by theanujdev** [comment]
@Aayush-hub I have removed some code and used OOP now. So it might look big but is far improved now.

**Review by Aayush-hub — COMMENTED** [review]
Not added the requested changes. Please add no. of attempts.

**Comment by theanujdev** [comment]
@Aayush-hub Sorry I don't get what you are saying. Are you saying that the game should run only once?

**Comment by Aayush-hub** [comment]
@ProdexOne Buddy you should finite number of attempts like you can give 5 chance and then average the win or loss and give fianlly who won.......computer or the user.

**Comment by theanujdev** [comment]
@Aayush-hub I hope this is what you wanted. Thanks.

**Review by Aayush-hub — APPROVED** [review]

**Pull request merged**
